.TH AHLL 1
.SH NAME
ahll \- Andy's Happy Little Language interpreter
.SH SYNOPSIS
.B ahll
[\fIFILE\fR]
.SH DESCRIPTION
.B ahll
is the interpreter for Andy's Happy Little Language, a whimsical
programming language designed to make coding fun and happy.
.SH EXAMPLES
To run a program:
.PP
.B ahll program.ahll
.PP
To start interactive mode:
.PP
.B ahll
.SH SEE ALSO
.BR bananacat (1)
.SH AUTHOR
andy64lol